# Controls clustering in the S1 model
- Beta_s: [2.1]
# Exponent of the hidden degree distribution
- gamma_s: [2.7]
# Size of the network
- Ns_obs: [1000]
# Average degree
- kmean_s: [10]
# Exponent of hidden degree distribution of Type 1 nodes (nodes)
- gamma_n: [8]
# Average degree of Type 1 nodes
- kmean_n: [20]
# Exponent of hidden degree distributino of Type 2 nodes (features)
- gamma_f: [5]
# Number of features
- N_f: [2000]
# Beta for bipartite model
- Beta_bi: [2.1]
# Correlation strength parameter
- nu: [0.0]
# Exponent for computing the probability of assiging each node to a class
- alpha: [-5, 0, 5]
# Number of labels
- N_labels: [2]
# Number of realizations
- ntimes: 1
